apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-namespace-labels
spec:
  rules:
  - name: enforce-environment-label
    match:
      resources:
        kinds:
        - Namespace
    validate:
      message: "Namespace must have the label environment: production"
      pattern:
        metadata:
          labels:
            environment: production
# here is a policy to ensure that all namespaces have a label `environment: production`